repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: mixed-line-ending

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: [--line-length=79, --skip-string-normalization]

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: [--profile=black, --line-length=79]

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies: [
          'flake8-annotations==3.1.1',
          'flake8-docstrings==1.7.0',
          'flake8-quotes==3.4.0',
          'flake8-dunder-all==0.5.0',
          'flake8-pyproject==1.2.3',
        ]
        args: [
          '--max-line-length=79',
          '--max-doc-length=79',
          '--ignore=ANN002,ANN003,ANN101,ANN102',
          '--extend-ignore=C901,ANN401',
          '--max-complexity=5',
          '--docstring-convention=google',
        ]
        exclude: ^tests/
        files: \.py$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        additional_dependencies: [
          "pydantic",
          "sqlalchemy2-stubs",
          "types-aiobotocore>=2.5.0",
          "types-setuptools",
          "types-freezegun",
        ]
        args: [
          '--ignore-missing-imports',
          '--show-error-codes',
          '--strict',
          '--exclude=__pycache__|venv',
          '--namespace-packages',
          '--explicit-package-bases',
        ]
        exclude: ^tests/
